### ISSUE TITLE
Enhancement request:  Thoughts on "even better"

### ISSUE THREAD

**Issue by mtboren** [ChristopherGLewis/ZertoModule#2]
Hello, @ChristopherGLewis-

Firstly, thanks much for the quite extensive module -- kudos so far!

As I started to look into using the module for our Zerto environment, I came up with a thought or two on making the module even better; things will that make module consumption more easy/natural from a PowerShell perspective.

The thoughts that I have are for things like:
- cmdlets for connecting/disconnecting to a ZVM that set/unset any necessary environment items, so user need not do so "manually"
  - like `Connect-ZertoZVM` and `Disconnect-ZertoZVM`
- singular noun `Get-*` cmdlets that, with no param, get _all_ of the given items, instead of singular and plural noun cmdlets for the same item type
  - example:  instead of `Get-ZertoVPG` and `Get-ZertoVPGs`, consolidate those into `Get-ZertoVPG`, which will get either specific VPG(s) with the right parameters/values, or all VPGs if no parameters are used
  - this is to adhere to the core/base behavior recommended in PowerShell by Microsoft, to which many (most?) users are accustomed
- standard use of approved verbs (`Commit` is "unapproved", verb of `New` in would be more fitting for the cmdlet currently named `Add-ZertoVPG`, etc)

You may have some/all of these on a roadmap, but I saw no roadmap in the repo, so I wanted to add an Enhancement Request with these ideas. Here is a GitHub Issue item via which to track this.

I will gladly fork/update/PR to help, but I wanted to get your take on such ideas before I start crunching code.  What are your thoughts?

Cheers!

**Comment by ChristopherGLewis** [comment]
great ideas - I think the get-* vs Get-*s is a great idea and that will probably be first.  

i've been struggling with the Commit issue - I think the verb Commit actually makes the most sense since it's what you're doing - you build up a VPGSetting, then commit it.  I've been hunting for a better verb, but I'm not satisfied with the choices - maybe Submit-VPGSettings would be better, or Complete-VPGSettings. 

The Add-ZertoVPG is kind of an issue - its a little customized for our personal usage, and really doesn't have a full match to the REST API.  I'm contemplating playing with this a little more, but haven't quite had the time.

thanks!

**Comment by ChristopherGLewis** [comment]
Did an update last night that addresses your second and third issue.  I'll work on the first shortly.

**Comment by mtboren** [comment]
Excellanté! I will check those out -- excited to see!  Thanks

**Comment by ChristopherGLewis** [comment]
Newest version (1.02) now has `Connect-ZertoZVM` and `Disconnect-ZertoZVM`.  Certainly a lot easier.

Chris

**Comment by mtboren** [comment]
Greets, @ChristopherGLewis -

Was just coming back to post the positive feedback on the other items you had updated, and see the `Connect-` and `Disconnect-` cmdlets now, too -- great!  Tried them out, and they work great (as expected). Thanks much -- that feature is definitely much more user-friendly, and the other updates make the module much more enjoyable, in my view!
